---

# ansible-playbook -i inventory -l eeCaServers

- hosts: upgradeEeServers:eeCaServers
  become: yes
  become_method: sudo
  gather_facts: true
  vars:
    ejbca_src_dir: "{{ ejbca_src_dir_name }}"
    ejbca_software_url: "{{ ejbca_software_ee_url }}"
  roles:
    - ansible-ejbca-upgrade

- hosts: upgradeEeServers:eeCaServers[0]
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    ejbca_src_dir: "{{ ejbca_src_dir_name }}"
    ejbca_software_url: "{{ ejbca_software_ee_url }}"    
  roles:
    - ansible-ejbca-complete-upgrade

- hosts: upgradeEeServers:eeRaServers
  become: yes
  become_method: sudo
  gather_facts: true
  vars:
    ejbca_src_dir: "{{ ejbca_src_dir_name }}_RA"
    ejbca_software_url: "{{ ejbca_software_ra_url }}"
  roles:
    - ansible-ejbca-upgrade

- hosts: upgradeEeServers:eeRaServers
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    ejbca_src_dir: "{{ ejbca_src_dir_name }}_RA"
    ejbca_software_url: "{{ ejbca_software_ra_url }}"
  roles:
    - ansible-ejbca-complete-upgrade

- hosts: upgradeEeServers:eeVaServers
  become: yes
  become_method: sudo
  gather_facts: true
  pre_tasks:
    - include_vars: customer_info/customer_vars.yml
  vars:
    ejbca_src_dir: "{{ ejbca_src_dir_name }}_VA"
    ejbca_software_url: "{{ ejbca_software_va_url }}"
  roles:
    - ansible-ejbca-upgrade

- hosts: upgradeEeServers:eeVaServers
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    ejbca_src_dir: "{{ ejbca_src_dir_name }}_VA"
    ejbca_software_url: "{{ ejbca_software_va_url }}"
  roles:
    - ansible-ejbca-complete-upgrade
    