---
# defaults file for ansible-ejbca-pkc11-client

ejbca_group: wildfly
ejbca_user: wildfly

use_softhsm: true

softhsm_gen_hsm_slots:
  - slot_name: SignServer_SLOT
    slot_so_pin: "{{ encrypted_signsrv_so_token_pin | default('foo123') }}" 
    slot_pin: "{{ encrypted_signsrv_token_pin | default('foo123') }}"
  - slot_name: DB_Protect_SLOT
    slot_so_pin: "{{ encrypted_signsrv_so_databaseprotection_token_pin | default('foo123') }}"
    slot_pin: "{{ encrypted_signsrv_databaseprotection_token_pin | default('foo123') }}"
