# roles/mariadb/tasks/config.yml
---

- name: Install server config file
  template:
    src: etc_my.cnf.d_server.cnf.j2
    dest: "{{ mariadb_config_server }}"
  tags: mariadb

- name: Install network config file
  template:
    src: etc_my.cnf.d_network.cnf.j2
    dest: "{{ mariadb_config_network }}"
  tags: mariadb

- name: Install custom config file
  template:
    src: etc_my.cnf.d_custom.cnf.j2
    dest: "{{ mariadb_config_custom }}"
  when: mariadb_custom_cnf|length != 0
  tags: mariadb

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ mariadb_swappiness }}"
    state: present
  when: mariadb_configure_swappiness|bool
  tags: mariadb

- name: Create mariadb log directory
  file:
    path: /var/log/mariadb
    state: directory
    mode: 0775
    owner: root
    group: mysql

- name: Move database directory when specified
  block:
    - name: Check if the new db directory location exists
      stat:
        path: "{{ mariadb_datadir }}"
      register: mariadb_dir_check
      changed_when: false

    - name: Create new db directory location
      file:
        path: "{{ mariadb_datadir }}"
        state: directory
        owner: "{{ mariadb_owner }}"
        group: "{{ mariadb_group }}"
      when: not mariadb_dir_check.stat.exists

    - name: Copy the contents of db datadir to {{ mariadb_datadir }}
      copy:
        src: /var/lib/mysql/
        dest: "{{ mariadb_datadir }}/"
        owner: "{{ mariadb_owner }}"
        group: "{{ mariadb_group }}"
        remote_src: true

    - name: Check SELinux status
      command: getenforce
      register: selinux_status
      changed_when: false

    - name: Configure SELinux for {{ mariadb_datadir }}
      sefcontext:
        target: "{{ mariadb_datadir }}(/.*)?"
        setype: mysqld_db_t
        state: present
        ftype: a
        reload: yes
      when: ('Enforcing' in selinux_status.stdout)
    
  when: mariadb_datadir is defined

- name: Ensure service is started
  systemd:
    name: "{{ mariadb_service }}"
    state: started
    enabled: true
  tags: mariadb
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7") or
        (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8") or
        (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") 

- name: Ensure service is started for RHEL 7 MariaDB
  systemd:
    name: "{{ rhel_mariadb_service }}"
    state: started
    enabled: true
  tags: mariadb
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7") 