---

- hosts: ejbcaSsServersAWS
  become: yes
  become_method: sudo
  pre_tasks:
    - include_vars: deployment_info/custom_aws_it_ss.yml
  roles:
    - ansible-hostname
    - ansible-role-mariadb
    - ansible-ejbca-wildfly
    - ansible-ejbca-pkc11-client
    - ansible-ss-prep
    - ansible-ss-peering
    - ansible-ss-admins
    - ansible-ss-crypto-workers
    - ansible-ss-gen-keys

- hosts: ejbcaCaServersAWS
  become: yes
  become_method: sudo
  gather_facts: false
  pre_tasks:
    - include_vars: deployment_info/custom_aws_it_ss.yml
  roles:
    - ansible-ejbca-certreq-cli

- hosts: ejbcaSsServersAWS
  become: yes
  become_method: sudo
  pre_tasks:
    - include_vars: deployment_info/custom_aws_it_ss.yml
  roles:
    - ansible-ss-workers
    - ansible-ss-httpd
